version: '3'
services:
  auth-api:
    build:
      context: .      
    ports:
      - "3040:3030"
    volumes:
      - ./:/app      
    environment:
      - DB_URL=${DB_URL}

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restgolang
    ports:
      - "5430:5432"